# Generated by Django 5.0.8 on 2024-10-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Почта"
                    ),
                ),
                ("password", models.CharField(verbose_name="Пароль")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "Ученик"),
                            ("teacher", "Преподаватель"),
                            ("admin", "Администратор"),
                        ],
                        default="student",
                        verbose_name="Роль",
                    ),
                ),
                ("name", models.CharField(verbose_name="Имя")),
                ("surname", models.CharField(verbose_name="Фамилия")),
                (
                    "birth_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата рождения"
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("male", "Мужской"),
                            ("female", "Женский"),
                            ("default", "Не указано"),
                        ],
                        default="default",
                        verbose_name="Пол",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, null=True, verbose_name="Телефон"),
                ),
                ("city", models.CharField(blank=True, null=True, verbose_name="Город")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата регистрации"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
