# Generated by Django 5.0.8 on 2024-10-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="isLogin",
            field=models.BooleanField(default=False),
        ),
    ]
